language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
- mvn clean org.codehaus.mojo.cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura